### PR TITLE
add scala dsl for IMetricsConsumer

### PR DESCRIPTION
**Pull request by duke-bartholomew**
An implementattion a la spout and bolt DSL, but for the IMetricsConsumer class

### CODE REVIEW

**Comment by velvia** [comment]
Thanks @duke-bartholomew, good idea

**Comment by duke-bartholomew** [comment]
@velvia  ,sorry about my late reply (busy time at the office)
Thanks for the comments, I'll tackle them one of the following days.

**Comment by duke-bartholomew** [comment]
@velvia - Thanks for the comments.
I added a unit test to show the usage of StormMetricsConsumer + do a sanity check on the implementation of this DSL.

**Comment by duke-bartholomew** [comment]
@velvia - ai, I messed up with the multiple scala versions ... I will correct this asap.
sorry about that.

**Comment by duke-bartholomew** [comment]
@velvia - what do you think? OK as it is, or do you want additional changes/tests ?

**Comment by velvia** [comment]
@duke-bartholomew thanks. Looks good now.  Will merge.

**Pull request merged**
