### PR TITLE
make storm config accessible in spout

### PR DESCRIPTION
**Pull request by duke-bartholomew**
Small update to be able to access the storm configuration from within the spout 'setup' functions.

### CODE REVIEW

**Comment by duke-bartholomew** [comment]
java.util.Map is replaced by JMap.
This being said, is there a specific reason why the Java Map is exposed in the _conf variable towards the Scala implementation?
It could be converted to a Scala Map so that the implementation can be kept pure Scala, no?
just an idea ...

**Comment by velvia** [comment]
@duke-bartholomew  I think it was just for ease of interfacing with the underlying Java API.    I'm in support of converting to a Scala Map for easier Scala developer use though.... as long as we provide easy methods or whatever so the conf still works or gets converted back.

**Comment by duke-bartholomew** [comment]
@velvia ok, thanks.
Can this pull request be merged? Or do you want me to do additional changes?

**Comment by velvia** [comment]
@duke-bartholomew thanks, :+1:

**Comment by duke-bartholomew** [comment]
great, thanks  :-)

**Pull request merged**
